Controllers/QuanLySachController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QUANLYSACH_MVC;

namespace QUANLYSACH_MVC.Controllers
{
    public class QuanLySachController : Controller
    {
        private SkyBrands_WebNCEntities3 db = new SkyBrands_WebNCEntities3();

        // GET: QuanLySach

        public ActionResult Index(int page = 1, int pageSize = 6)
        {
            if(Session["admin"] == null)
                return RedirectToAction("../Admin/Login");

            var totalRecords = db.Books.Count();
            var totalPages = (int)Math.Ceiling((double)totalRecords / pageSize);

            var dataToDisplay = db.Books.OrderBy(x => x.bookId)
                                         .Skip((page - 1) * pageSize)
                                         .Take(pageSize)
                                         .ToList();

            ViewBag.CurrentPage = page;
            ViewBag.TotalPages = totalPages;
            ViewBag.HasPreviousPage = (page > 1);
            ViewBag.HasNextPage = (page < totalPages);

            return View(dataToDisplay);
        }

        // GET: QuanLySach/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Books books = db.Books.Find(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // GET: QuanLySach/Create
        public ActionResult Create()
        {
            if (Session["admin"] == null)
                return RedirectToAction("../Admin/Login");

            ViewBag.cid = new SelectList(db.Categories, "categoryId", "categoryName");
            ViewBag.pcid = new SelectList(db.PublishingCompany, "companyId", "companyName");
            return View();
        }

        // POST: QuanLySach/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Books books, HttpPostedFileBase bookImage)
        {
            if (ModelState.IsValid && bookImage != null && bookImage.ContentLength > 0)
            {
                ViewBag.cid = new SelectList(db.Categories, "categoryId", "categoryName", books.cid);
                ViewBag.pcid = new SelectList(db.PublishingCompany, "companyId", "companyName", books.pcid);
                // Lưu ảnh vào thư mục trong ứng dụng
                var fileName = Path.GetFileName(bookImage.FileName);
                var path = Path.Combine(Server.MapPath("~/img/books"), fileName);
                bookImage.SaveAs(path);
                // Xử lý lưu thông tin về ảnh vào cơ sở dữ liệu
                string imagePath = Path.GetFileName(bookImage.FileName);
                Books book = new Books { bookId = books.bookId, bookName = books.bookName, bookImage = imagePath, author = books.author, price = books.price, quantity = books.quantity, publishingYear = books.publishingYear, language = books.language, numberPage = books.numberPage, form = books.form, weight = books.weight, bookDescribe = books.bookDescribe, cid = books.cid, pcid = books.pcid };
                // Redirect hoặc trả về view cần thiết sau khi upload thành công
                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(books);
        }

        // GET: QuanLySach/Edit/5
        public ActionResult Edit(string id)
        {
            if (Session["admin"] == null)
                return RedirectToAction("../Admin/Login");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Books books = db.Books.Find(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            ViewBag.cid = new SelectList(db.Categories, "categoryId", "categoryName", books.cid);
            ViewBag.pcid = new SelectList(db.PublishingCompany, "companyId", "companyName", books.pcid);
            return View(books);
        }

        // POST: QuanLySach/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Books books, HttpPostedFileBase bookImage)
        {
            if (ModelState.IsValid && bookImage != null && bookImage.ContentLength > 0)
            {
                ViewBag.cid = new SelectList(db.Categories, "categoryId", "categoryName", books.cid);
                ViewBag.pcid = new SelectList(db.PublishingCompany, "companyId", "companyName", books.pcid);
                // Lưu ảnh vào thư mục trong ứng dụng
                var fileName = Path.GetFileName(bookImage.FileName);
                var path = Path.Combine(Server.MapPath("~/img/books"), fileName);
                bookImage.SaveAs(path);
                // Xử lý lưu thông tin về ảnh vào cơ sở dữ liệu
                string imagePath = Path.GetFileName(bookImage.FileName);
                Books book = new Books { bookId = books.bookId, bookName = books.bookName, bookImage = imagePath, author = books.author, price = books.price, quantity = books.quantity, publishingYear = books.publishingYear, language = books.language, numberPage = books.numberPage, form = books.form, weight = books.weight, bookDescribe = books.bookDescribe, cid = books.cid, pcid = books.pcid };
                // Redirect hoặc trả về view cần thiết sau khi upload thành công
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
 
            return View(books);
        }

        // GET: QuanLySach/Delete/5
        public ActionResult Delete(string id)
        {
            if (Session["admin"] == null)
                return RedirectToAction("../Admin/Login");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Books books = db.Books.Find(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // POST: QuanLySach/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Books books = db.Books.Find(id);
            db.Books.Remove(books);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/QuanLySach/Delete.cshtml
@model QUANLYSACH_MVC.Books

@{
    ViewBag.Title = "Delete";
    string formattedAmount = string.Format("{0:C0}", Model.price);
}

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Skybooks Clone by manod</title>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <link rel="stylesheet" type="text/css" href="~/Content/admin.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/admin_mvc.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/skybooks.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/grid.css" />
    <link rel="icon" type="image/x-icon" href="~/img/favicon.icon.png" />
    <!-- <link rel="stylesheet" href="/skybooks/css/responsive_home.css"> -->
    <!-- [if lt IE 9]>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js" integrity="sha512-qWVvreMuH9i0DrugcOtifxdtZVBBL0X75r9YweXsdCHtXUidlctw7NXg5KVP3ITPtqZ2S575A0wFkvgS2anqSA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <![endif]-->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
</head>
<body>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <div class="wrapper grid">
        <div class="admin_header grid">
            <div class="admin_top grid wide row">
                <div class="admin_top_left l-6 m-6 c-6">
                    <div class="logo"><img src="~/img/logo.png" alt="Skybooks Logo" /></div>
                </div>

                <div class="admin_top_right l-6 m-6 c-6">
                    <div class="infor_account">
                        <a class="account" href="~/TrangChu/ThongTin"><i class="fa fa-user" aria-hidden="true"></i> <span>@Session["admin"]</span></a>
                    </div>
                    <div class="logout_account">
                        <a class="logout" href="~/TrangChu/DangXuat"><i class="fa fa-sign-in" aria-hidden="true"></i> <span>Đăng xuất</span></a>
                    </div>
                </div>
            </div>
        </div>
        <!--end-header-top-->

        <div class="admin_center grid">
            <div class="admin_middle grid wide row">
                <div class="admin_middle_left no-gutters l-2">
                    <div>ADMIN</div>
                    <div class="home_page">
                        <a href="~/Admin/Home"><i class="fa fa-home" aria-hidden="true"></i> <span>Home</span></a>
                    </div>
                    <div class="block_management">
                        <ul class="block_management_list">
                            <li>
                                <div class="block_management_list_items">
                                    <a href="~/QuanLyTaiKhoan/Index">
                                        <i class="fa fa-user" aria-hidden="true"></i>
                                        <span>Quản lý Tài khoản</span>
                                    </a>
                                </div>
                            </li>
                            <li>
                                <div class="block_management_list_items">
                                    <a href="~/QuanLyTheLoai/Index">
                                        <i class="fa fa-book" aria-hidden="true"></i>
                                        <span>Quản lý Thể loại</span>
                                    </a>
                                </div>
                            </li>
                            <li>
                                <div class="block_management_list_items" id="management_books">
                                    <a href="~/QuanLySach/Index">
                                        <i class="fa fa-book" aria-hidden="true"></i>
                                        <span>Quản lý Sách</span>
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="admin_middle_right no-gutters l-10">
                    <div class="title_management">XÓA SÁCH</div>
                    <h3>Bạn có chắc chắn muốn xóa không?</h3>
                    <div>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                Mã sách:
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.bookId)
                            </dd>

                            <dt>
                                Tên sách:
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.bookName)
                            </dd>

                            <dt>
                                Hình ảnh:
                            </dt>

                            <dd>
                                <img width="120px" height="120px" src="~/img/books/@Html.DisplayFor(model => model.bookImage)" />
                            </dd>

                            <dt>
                                Tác giả:
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.author)
                            </dd>

                            <dt>
                                Đơn giá:
                            </dt>

                            <dd>
                                @formattedAmount
                            </dd>

                            <dt>
                                Số lượng:
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.quantity)
                            </dd>

                            <dt>
                                Năm XB:
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.publishingYear)
                            </dd>

                            <dt>
                                Ngôn ngữ:
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.language)
                            </dd>

                            <dt>
                                Số trang:
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.numberPage)
                            </dd>

                            <dt>
                                Hình thức:
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.form)
                            </dd>

                            <dt>
                                Trọng lượng:
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.weight)
                            </dd>

                            <dt>
                                Mô tả:
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.bookDescribe)
                            </dd>

                            <dt>
                                Thể loại:
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Categories.categoryName)
                            </dd>

                            <dt>
                                NXB:
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.PublishingCompany.companyName)
                            </dd>

                        </dl>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <input type="submit" value="Xóa" class="btn_primary" />
                                @Html.ActionLink(" | Quay lại danh sách", "Index", null, new { @class = "link_comeback" })
                            </div>
                        }
                    </div>
                </div>
            </div>
            <!--end-middle-->
        </div>
    </div>
</body>
</html>

Views/QuanLySach/Edit.cshtml
@model QUANLYSACH_MVC.Books

@{
    ViewBag.Title = "Edit";
    string formattedAmount = string.Format("{0:C0}", Model.price);
}

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Skybooks Clone by manod</title>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <link rel="stylesheet" type="text/css" href="~/Content/admin.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/admin_mvc.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/skybooks.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/grid.css" />
    <link rel="icon" type="image/x-icon" href="~/img/favicon.icon.png" />
    <!-- <link rel="stylesheet" href="/skybooks/css/responsive_home.css"> -->
    <!-- [if lt IE 9]>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js" integrity="sha512-qWVvreMuH9i0DrugcOtifxdtZVBBL0X75r9YweXsdCHtXUidlctw7NXg5KVP3ITPtqZ2S575A0wFkvgS2anqSA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <![endif]-->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
</head>
<body>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <div class="wrapper grid">
        <div class="admin_header grid">
            <div class="admin_top grid wide row">
                <div class="admin_top_left l-6 m-6 c-6">
                    <div class="logo"><img src="~/img/logo.png" alt="Skybooks Logo" /></div>
                </div>

                <div class="admin_top_right l-6 m-6 c-6">
                    <div class="infor_account">
                        <a class="account" href="~/TrangChu/ThongTin"><i class="fa fa-user" aria-hidden="true"></i> <span>@Session["admin"]</span></a>
                    </div>
                    <div class="logout_account">
                        <a class="logout" href="~/TrangChu/DangXuat"><i class="fa fa-sign-in" aria-hidden="true"></i> <span>Đăng xuất</span></a>
                    </div>
                </div>
            </div>
        </div>
        <!--end-header-top-->

        <div class="admin_center grid">
            <div class="admin_middle grid wide row">
                <div class="admin_middle_left no-gutters l-2">
                    <div>ADMIN</div>
                    <div class="home_page">
                        <a href="~/Admin/Home"><i class="fa fa-home" aria-hidden="true"></i> <span>Home</span></a>
                    </div>
                    <div class="block_management">
                        <ul class="block_management_list">
                            <li>
                                <div class="block_management_list_items">
                                    <a href="~/QuanLyTaiKhoan/Index">
                                        <i class="fa fa-user" aria-hidden="true"></i>
                                        <span>Quản lý Tài khoản</span>
                                    </a>
                                </div>
                            </li>
                            <li>
                                <div class="block_management_list_items">
                                    <a href="~/QuanLyTheLoai/Index">
                                        <i class="fa fa-book" aria-hidden="true"></i>
                                        <span>Quản lý Thể loại</span>
                                    </a>
                                </div>
                            </li>
                            <li>
                                <div class="block_management_list_items" id="management_books">
                                    <a href="~/QuanLySach/Index">
                                        <i class="fa fa-book" aria-hidden="true"></i>
                                        <span>Quản lý Sách</span>
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="admin_middle_right no-gutters l-10">
                    <div class="title_management">CẬP NHẬT SÁCH</div>
                    @using (Html.BeginForm("Edit", "QuanLySach", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-horizontal" style="display:flex">
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.bookId)

                            <div style="flex:50%">
                                <div class="form-group">
                                    <label class="control-label col-md-2">Tên sách:</label>
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.bookName, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.bookName, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-2">Hình ảnh:</label>
                                    <div class="col-md-10">
                                        <input type="file" name="bookImage" />
                                        @Html.ValidationMessageFor(model => model.bookImage, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-2">Tác giả:</label>
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.author, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.author, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-2">Đơn giá:</label>
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-2">Số lượng:</label>
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.quantity, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.quantity, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-2">Năm XB:</label>
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.publishingYear, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.publishingYear, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-2">Ngôn ngữ:</label>
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.language, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.language, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                            </div>
                            <div style="flex:50%">
                                <div class="form-group">
                                    <label class="control-label col-md-2">Số trang:</label>
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.numberPage, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.numberPage, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-2">Hình thức:</label>
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.form, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.form, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-2">Trọng lượng:</label>
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.weight, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.weight, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-2">Mô tả:</label>
                                    <div class="col-md-10">
                                        @Html.TextAreaFor(model => model.bookDescribe, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.bookDescribe, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-2">Thể loại:</label>
                                    <div class="col-md-10">
                                        @Html.DropDownList("cid", null, htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.cid, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-2">NXB:</label>
                                    <div class="col-md-10">
                                        @Html.DropDownList("pcid", null, htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.pcid, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Lưu" class="btn_primary" />
                            </div>
                        </div>
                    }

                <div>
                    @Html.ActionLink("Quay lại danh sách", "Index", null, new { @class = "link_comeback" })
                </div>
                </div>
            </div>
            <!--end-middle-->
        </div>
    </div>
</body>
</html>